In [1]:
#check Numpy Lib Version
import numpy as np
print(np.__version__)

1.18.5


In [3]:
#1- 1D Array of string
s = np.array(["salma","aqsa","anum","Aini"])
print(s) #Print the elements
s #print elemenets with thheir type

['salma' 'aqsa' 'anum' 'Aini']


array(['salma', 'aqsa', 'anum', 'Aini'], dtype='<U5')

In [10]:
#2- 2D Array of Number
j = np.array([[4,6,8],[9,3,1]], dtype= int) #with dtype
k = np.array([[4,6,8],["salma",3,1]]) #without
j

array([[4, 6, 8],
       [9, 3, 1]])

In [11]:
#3- arange func 
t = np.arange(1,20,2) #start,end, diifence(stepsize)
t

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
#4- linspace func
p = np.linspace(0,10,6) #start,end, num (num of sample)
p

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
#5- zeros func
c = np.zeros((5))
c

array([0., 0., 0., 0., 0.])

In [19]:
#6- full func
f = np.full((4,4),0)#4x4 array with all values zero
f

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
#7- eye func
e = np.eye(3) #diagnol array
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#8- ones func
o = np.ones((7))
o

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
#9- random.randint integer
r = np.random.randint(10, size=(6,6))
r

array([[0, 0, 1, 6, 1, 0],
       [5, 5, 6, 1, 4, 5],
       [5, 7, 9, 2, 2, 3],
       [2, 3, 3, 8, 9, 2],
       [1, 7, 1, 3, 2, 5],
       [3, 1, 4, 8, 9, 9]])

In [24]:
#10- random.rand floating
f = np.random.rand(3,5)*100#rows,column,samplenum 0-100
f

array([[72.51322528, 37.09293458, 64.93057433, 29.16888836, 76.72827607],
       [86.8128309 , 26.7992541 , 39.0238997 , 94.926873  ,  7.48365174],
       [88.19696706, 93.38063355, 26.3550255 ,  9.72682903,  1.38464416]])

In [38]:
#11- reshape func
b = np.arange(1,9) #start,end
newarr = b.reshape(4, 2)
newarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
#12- shape func
arr = np.array([["salma","aqsa","aini"],["RaziUllah","Mishaal"]], dtype = list)
arr = arr.shape
arr

(2,)

In [40]:
#13- dtype(datatype)
dt = np.array([0,8,6,4,2])
dt = dt.dtype
dt

dtype('int64')

In [41]:
#14- ndim(dimension)
n = np.array([(1,2,3),(4,5,6)])
n = n.ndim
n

2

In [43]:
#15- size of array

i = np.array(["fsd","lhr","isb","mul","punj"])
i = i.size
i

5

In [44]:
#16- astype
y = np.array([9,8,7,6,5,4,3,2,1])
y = y.astype(float)
y

array([9., 8., 7., 6., 5., 4., 3., 2., 1.])

In [45]:
#17- flattern (converting 2D into 1D array)
ar = np.array([(1,2,3),(4,5,6)])
ar = ar.flatten()
ar

array([1, 2, 3, 4, 5, 6])

In [46]:
#18- transpose (3x2 to 2x3 array)
t = np.array([1,2,3,4,5,6])
t = t.reshape((3,2))
t = t.T
t

array([[1, 3, 5],
       [2, 4, 6]])

In [49]:
#19- resize func
rr = np.array([1,2,3,4,5,6])
rr = np.resize(rr, (3,4))
rr

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [50]:
#20- tolist func
l = np.array([(1,2,3),(4,5,6)])
l = l.tolist()
l

[[1, 2, 3], [4, 5, 6]]

In [52]:
#21- sort func
s = np.array([(3,1,4),(0,2,5)])
s = np.sort(s, axis= 1) #asic 0 is for column and axis 1 is for rows
s

array([[1, 3, 4],
       [0, 2, 5]])

In [53]:
#22- append func
ap = np.array(["salma","Kansa","Isha"])
ap = np.append(ap,"Maryam")
ap

array(['salma', 'Kansa', 'Isha', 'Maryam'], dtype='<U6')

In [55]:
#23- concatenate func
a1 = np.array([(1,2,3),(4,5,6)])
a2 = np.array([(3,1,4),(0,2,5)])
con  = np.concatenate((a1,a2), axis= 1)
con

array([[1, 2, 3, 3, 1, 4],
       [4, 5, 6, 0, 2, 5]])

In [56]:
#24- hsplit(for index)
sp = np.array([1,2,3,4,5,6])
sp = np.hsplit(sp, 2)
sp

[array([1, 2, 3]), array([4, 5, 6])]

In [57]:
#25- array_split func
asp = np.array([1,2,3,4,5,6])
asp = np.array_split(asp, 3)
asp

[array([1, 2]), array([3, 4]), array([5, 6])]

In [58]:
#26- delete
de = np.array(["salma","anum","aqsa"])
de = np.delete(de,1, axis= 0) #index 1 
de

array(['salma', 'aqsa'], dtype='<U5')

In [59]:
#27- insert
ins = np.array(["salma","anum","aqsa"])
ins = np.insert(ins, 2, "aini") #index 2
ins

array(['salma', 'anum', 'aini', 'aqsa'], dtype='<U5')

In [62]:
#28- slicing
s1 = np.array([1,2,3,4,5,6,7,8,9,10])
s1 = s1[0:-1]
s1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
#29 - selecting element
se = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2d array
se = se[1,2]
se

8

In [68]:
#30- slicing with 0 index
s2= np.array([[1,2,3,4,5],[6,7,8,9,10]])
s2 = s2[:,0]
s2

array([1, 6])

In [70]:
#31- max
mx= np.array([222,234,112,255,410])
mx = np.max(mx)
mx

410

In [71]:
#32- min
mn = np.array([2,4,0,0,10])
mn = np.min(mn)
mn

0

In [72]:
#33- floor
fl = np.array([1.3,2.7,3.5])
fl = np.floor(fl)
fl

array([1., 2., 3.])

In [73]:
#33- ceil
f2 = np.array([1.3,2.7,3.5])
f2 = np.ceil(f2)
f2

array([2., 3., 4.])

In [74]:
#34- round
ro = np.array([1.3,2.7,3.5])
ro = np.round(ro)
ro

array([1., 3., 4.])

In [76]:
#35- absolute
ab = np.array([1.3,2,3.5])
ab = np.abs(ab)
ab

array([1.3, 2. , 3.5])

In [77]:
#36- log
lg = np.array([1,30,45,60,90])
lg = np.log(lg)
lg

array([0.        , 3.40119738, 3.80666249, 4.09434456, 4.49980967])

In [78]:
#37- cos
cs = np.array([0,30,45,60,90])
cs = np.cos(cs)
cs

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [79]:
#38- sin
sn = np.array([0,30,45,60,90])
sn = np.sin(sn)
sn

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [80]:
#39- exponenet
ex = np.array([1,2,3,4,5])
exp = np.exp(ex)
exp

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [82]:
#40- equal array
a1 = np.array(["salma","aqsa"])
a2 = np.array(["salma","aqsa"])
ans  = np.array_equal(a1,a2)
ans

True

In [83]:
#41- power 
pw = np.array([1,3,5,7,9,11])
poe  = np.power(pw,2)
poe

array([  1,   9,  25,  49,  81, 121])

In [84]:
#42- square
sq = np.array([1,4,9,10,16,25])
squ = np.square(sq)
squ

array([  1,  16,  81, 100, 256, 625])

In [86]:
#43- sqrt (squeare root)
sqr = np.array([1,2,3,4])
sqr = np.sqrt(sqr)
sqr

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [88]:
#44- add
ad = np.array([4,9,6,2,15,10])
ad  = np.add(ad,3)
ad


array([ 7, 12,  9,  5, 18, 13])

In [89]:
#45- substract
sub1 = np.array([4,9,6,2,15,10])
sub2 = np.array([2,4,6,8,10,12])
sb  = np.subtract(sub2,sub1)
sb

array([-2, -5,  0,  6, -5,  2])

In [91]:
#46- multiply
m1 = np.array([1,3,5,7,9,11])
m2 = np.copy(m1)
mu = np.multiply(m2,m1)
mu

array([  1,   9,  25,  49,  81, 121])

In [92]:
#47-divide
d1 = np.array([2,6,12,16,30,60])
d2 = np.array([2,4,6,8,10,12])
div  = np.divide(d1,d2)
div

array([1. , 1.5, 2. , 2. , 3. , 5. ])

In [96]:
#48- mean
me = np.array([[2,6,3],[5,9,15]])
me = np.mean(me,axis=1)
me

array([3.66666667, 9.66666667])

In [97]:
#49-median
md = np.array([[2,6,3],[5,9,15]])
md = np.median(md,axis=1)
md

array([3., 9.])

In [99]:
#50- sum of variance
su = np.array([[2,6,3],[5,9,15]])
sm = su.sum(axis=1)
v = np.var(sm)
v

81.0